"""upgrade animal model for dashboard

Revision ID: 0a61651a2f59
Revises: 343fee490054
Create Date: 2026-02-03 18:43:55.747971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a61651a2f59'
down_revision = '343fee490054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('health_status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('daily_feed_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rfid_tag', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_vaccination_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('next_vaccination_date', sa.Date(), nullable=True))
        batch_op.create_unique_constraint(None, ['rfid_tag'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('next_vaccination_date')
        batch_op.drop_column('last_vaccination_date')
        batch_op.drop_column('location')
        batch_op.drop_column('rfid_tag')
        batch_op.drop_column('daily_feed_kg')
        batch_op.drop_column('weight')
        batch_op.drop_column('health_status')
        batch_op.drop_column('status')

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
